[package]
name = "slievr"
version = "0.1.0"
authors = ["slievr"]

[dependencies]
rocket = "0.3.4"
rocket_codegen = "0.3.4"

[dependencies.rocket_contrib]
version = "0.3.4"
features = ["handlebars_templates"]
