[package]
name = "slievr"
version = "0.1.0"
authors = ["slievr"]

[dependencies]
rocket = "0.3.4"
rocket_codegen = "0.3.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "0.3.4"
features = ["handlebars_templates"]
